# Write SQL queries to perform the following tasks using the Sakila database:

use sakila;
# 1.List the number of films per category.
select * from film;
select * from category;
select c.name, count(*) as total_films
from film flm
inner join film_category flmc
on flm.film_id = flmc.film_id
inner join category c
on flmc.category_id = c.category_id
group by c.name;


# 2.Retrieve the store ID, city, and country for each store.
select * from store;
select * from address;
select * from city;
select * from country;

select st.store_id, ct.city, cn.country
from store as st
inner join address ad
on st.address_id = ad.address_id
inner join city ct
on ad.city_id = ct.city_id
inner join country cn
on ct.country_id = cn.country_id;


# 3.Calculate the total revenue generated by each store in dollars.
select * from store;
select * from staff;
select * from payment;

select st.store_id, sum(pt.amount) as revenue
from store st
inner join staff sf
on st.store_id = sf.store_id
inner join payment pt
on sf.staff_id = pt.staff_id
group by st.store_id;


# 4.Determine the average running time of films for each category.
select * from category;
select * from film_category;
select * from film;

select ctn.name as category_name, round(avg(f.length),2) as avg_runnung_time
from category ctn
inner join film_category fct
on ctn.category_id = fct.category_id
inner join film f
on fct.film_id = f.film_id
group by ctn.name;	
